const timeZoneList = [
        { country: 'United States', tz: 'Pacific/Midway' , offset: 'GMT-11:00', currency:'US'},
        { country: 'United States', tz: 'Pacific/Honolulu', offset: 'GMT-10:00', currency:'US'},
        { country: 'United States', tz: 'America/Juneau', offset: 'GMT-8:00', currency:'US'},
        { country: 'United States', tz: 'America/Los_Angeles', offset: 'GMT-7:00', currency:'US'},
        { country: 'United States', tz: 'America/Phoenix', offset: 'GMT-7:00', currency:'US'},
        { country: 'United States', tz: 'America/Chicago', offset: 'GMT-6:00', currency:'US'},
        { country: 'United States', tz: 'America/New_York', offset: 'GMT-5:00', currency:'US'},
        { country: 'United States', tz: 'America/Santiago', offset: 'GMT-4:00', currency:'US'},
        { country: 'United States', tz: 'America/Sao_Paulo', offset: 'GMT-3:00', currency:'US'},
        { country: 'South_Georgia', tz: 'Atlantic/South_Georgia', offset:'GMT-2:00', currency:null},
        { country: 'Portugal', tz: 'Atlantic/Azores', offset:'GMT-1:00', currency:'EUR'},
        { country: 'France', tz: 'Europe/Paris', offset:'GMT+1:00', currency:'EUR'},
        { country: 'Africa', tz: 'Africa/Cairo', offset:'GMT+2:00', currency:null},
        { country: 'Qatar', tz: 'Asia/Qatar', offset:'GMT+3:00', currency:null},
        { country: 'Saudi Arabia', tz: 'Asia/Dubai', offset:'GMT+4:00', currency:'SR'},
        { country: 'India', tz: 'Asia/Karachi', offset:'GMT+5:00', currency:'INR'},
        { country: 'India', tz: 'Asia/Kathmandu', offset:'GMT+5:45', currency:'INR'},
        { country: 'India', tz: 'Asia/Dhaka', offset:'GMT+6:00', currency:'INR'},
        { country: 'Bangkok', tz: 'Asia/Bangkok', offset:'GMT+7:00', currency:'THB'},
        { country: 'China', tz: 'Asia/Hong_Kong', offset:'GMT+8:00', currency:'CNY'},
        { country: 'Japan', tz: 'Asia/Tokyo', offset:'GMT+9:00', currency:'JPY'},
        { country: 'Australia', tz: 'Australia/Adelaide', offset:'GMT+10:30', currency:'EUR'},
        { country: 'Australia', tz: 'Australia/Melbourne', offset:'GMT+11:00', currency:'EUR'},
        { country: 'Russia', tz: 'Asia/Magadan', offset:'GMT+11:00', currency:'RUB'},
        { country: 'Fiji', tz: 'Pacific/Fiji', offset:'GMT+12:00', currency:'FJD'},
        { country: 'India', tz: 'Asia/Kolkata', offset:'GMT+5:30', currency:'INR'},
    ]

module.exports.timeZoneListToSend = timeZoneList